apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: json-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
        - name: json-server
          image: image-registry.openshift-image-registry.svc:5000/youssef-project/json-server:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          emptyDir: {}
