# Deployment pour le Frontend Angular
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: youssef-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # On pointe vers le registre interne où tu viens de build l'image
          image: image-registry.openshift-image-registry.svc:5000/youssef-project/frontend:latest
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          # On simplifie les probes pour le premier déploiement
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10

---
# Service pour exposer le frontend en interne
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: youssef-project
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
