# Route OpenShift SANS TLS pour éviter l'erreur wrongHost
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: youssef-project
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 8080
  # La section tls a été supprimée
