apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: json-server
  labels:
    app: json-server
spec:
  replicas: 1
  selector:
    app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
        - name: json-server
          image: json-server:latest
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
          livenessProbe:
            httpGet:
              path: /users
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /users
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - json-server
        from:
          kind: ImageStreamTag
          name: json-server:latest
