name: CI/CD OpenShift

on:
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install oc
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login OpenShift
        run: |
          # Utilisation de tes secrets avec la syntaxe oc login
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify

      - name: Start builds
        run: |
          # On sélectionne le bon projet au cas où
          oc project ${{ secrets.OPENSHIFT_NAMESPACE }}

          # Lancement des builds binaires (comme on faisait sur ton PC)
          oc start-build json-server --from-dir=docker/backend --follow
          oc start-build frontend --from-dir=. --follow
